### ISSUE TITLE
Switch from 16 DIFF to 32 GRND (E14-140MD)

### ISSUE THREAD

**Issue by antipirin** [RAA80/python-lcomp#2]
Здравствуйте. 
Относительно нубский вопрос возник - необходимо переключить режим E14-140MD из дифференциального с 16 каналами в режим с общей землей, с 32 каналами. В целях изучения, использую готовый пример из репозитория - [example.py](https://github.com/RAA80/python-lcomp/blob/main/example/example.py).
В [e140.py](https://github.com/RAA80/python-lcomp/blob/main/lcomp/device/e140.py) есть следующие строчки:
```
# тип канала E140
CH_DIFF = 0             # дифференциальный канал
CH_NULL = 16            # калибровка нуля
CH_GRND = 32            # канал с общей землей
```
Но они нигде не используются, соответственно, мне до конца оставалось неясным - где их задавать. 
Полез в [Руководство программиста Л-Кард](https://www.lcard.ru/download/examples/lcomp/manual.pdf), где обнаружил структуру ADC_PAR_0 в которой упоминается переключение каналов:

![image](https://github.com/RAA80/python-lcomp/assets/114661071/3cfc3685-ca6e-4984-9156-c6ce5a50223f)

Исходя из этого, предположил, что необходимо в [example.py](https://github.com/RAA80/python-lcomp/blob/main/example/example.py) задать: 
```
adcPar.t3.Chn[5] = 1 
```
Однако, как показала практика - это предположение все еще неправильное. Очень нужна подсказка - как все же правильно переключать режимы портов на режим общей земли.
Спасибо!

**Comment by RAA80** [comment]
Скорее всего adcPar.t3.Chn[5] = 32, т.к. общий - 5-ый бит (2^5=32). Либо просто adcPar.t3.Chn[5] = CH_GRND. И в Chn[5] - 5 это номер канала из массива с номерами каналов, а не бита

**Comment by antipirin** [comment]
> И в Chn[5] - 5 это номер канала из массива с номерами каналов, а не бита

В конечном итоге я это понял и осознал, но к решению проблемы не приблизился)) И это нас приводит тогда к тому, что режимы должны переключаться как-то так:
`adcPar.t3.Chn[0] = e140.CH_0 | e140.V10000 | e140.CH_GRND`
Но тут возникает еще обратная сторона - нам, получается, необходимо тогда задавать в каждом канале бит вкл/выкл. режима общей земли. А я исходил из предположения, что этот режим задается одним битом в одном месте.
Иначе, может возникнуть ситуация, когда 1 канал (X1) находится в режиме общей земли, а канал 17 (Y1) находится в дифференциальном режиме, например. 

![image](https://github.com/RAA80/python-lcomp/assets/114661071/00be3bcc-1013-4dca-915a-e4c3447c3a66)

**Comment by RAA80** [comment]
Как сделать правильно, я думаю, надо спросить на форуме Lcard.

**Comment by antipirin** [comment]
Ок. Решил сначала спросить у вас, как у автора библиотеки с которой работаю, т.к. увидел, что типы каналов обозначены у устройства, в принципе =)

**Comment by RAA80** [comment]
Я с режимом с общей землей не работал. Самому интересно как это запрограммировать

**Comment by antipirin** [comment]
Так. В конечном итоге, у меня заработал такой вариант `adcPar.t3.Chn[0] = e140.CH_0 | e140.V10000 | e140.CH_GRND` для включения канала **X1** в режим общей земли. 
Для того, чтобы включить и **Y1** в режим общей земли - `adcPar.t3.Chn[16] = e140.CH_0 | e140.V10000 | e140.CH_GRND | 16`, либо можно ввести переменную, скажем, `CH_Y = 16` в [e140.py](https://github.com/RAA80/python-lcomp/blob/main/lcomp/device/e140.py) и тогда включение всех портов в режиме общей земли будет выглядеть так:

```
adcPar.t3.Chn[0] = e140.CH_0 | e140.V10000 | e140.CH_GRND           
...     
adcPar.t3.Chn[15] = e140.CH_15 | e140.V10000 | e140.CH_GRND
###Y lines###
adcPar.t3.Chn[16] = e140.CH_0 | e140.V10000 | e140.CH_GRND | e140.CH_Y
...
adcPar.t3.Chn[31] = e140.CH_15 | e140.V10000 | e140.CH_GRND | e140.CH_Y
```
Предлагаю ввести пояснение в комментарии в [example.py](https://github.com/RAA80/python-lcomp/blob/main/example/example.py), поясняющие этот момент с включением общей земли =)

**Comment by RAA80** [comment]
Спасибо, поправлю.
